---
"$schema": http://json-schema.org/draft-07/schema#
"$id": urn:mef:lso:spec:sonata:EnniCommon:v1.0.0:inventory
title: 
    MEF LSO Sonata - Carrier Ethernet ENNI Common (Inventory) Product Specification
    # MEF Forum - Date: 20201220  Edit-level: 178
    # File: accessEline/inventory/carrierEthernetEnniCommon.yaml
description:  >-
    These are the technical details that need to be agreed to by
    the Network Operators in order for their Carrier Ethernet Networks
    to be interconnected by the ENNI.
properties:
    peeringIdentifier:
        description:  >-
            MEF 26.2 §9.1 - An identifier for the ENNI intended for operations
            purposes by the interconnecting Operators at the ENNI.
        type: string
        minLength: 1
        maxLength: 45
        pattern: "[\x20-\x7F]+"
    listOfPhysicalLinks:
        description:  >-
            MEF 26.2 §9.2 and 9.3 - This Service Attribute combines several
            of the MEF 26.2 Objects into a single n-tuple that is consistent
            with the way this information is described in MEF 10.4. The value
            of the ENNI List of Physical Links Service Attribute is a list
            of 5-tuples of the form <id,pl,fs,pt,cn>, with one list item for
            each physical link. The value of id is an identifier for the physical
            link. The value of pl specifies a physical layer. fs indicates
            if synchronous Ethernet is used on the physical link corresponding
            to the 5-tuple and has the value either Enabled or Disabled. The
            value of pt indicates if the Precision Time Protocol is used on
            the physical link corresponding to the 5-tuple and has the value
            either Enabled or Disabled. The value of cn specifies the type
            of connector used at the UNI.
        type: array 
        minItems: 1
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetExternalInterfaces.yaml#/definitions/EnniPhysicalLink"
    serviceFrameFormat:
        description:  >-
            MEF 26.2 §9.3 - The ENNI Frame Format Common Attribute has
            the value Ethernet MAC Frame conforming to Clause 3 of IEEE 802.3-2012.
        type: string
        enum:
            - "802.3-2012"
    linkAggregation:
        description:  >-
            MEF 26.2 §9.5 - If the ENNI is composed of multiple physical
            links this Service Attribute indicates how they are combined using
            Link Aggregation.
        # See additional validation notes in the manual
        type: string
        enum:
            - "NONE"
            - "2_LINK_ACTIVE_STANDBY"
            - "ALL_ACTIVE"
            - "OTHER"
    portConversation:
        description:  >-
            MEF 26.2 §9.6 - A mapping of Port Conversation IDs (i.e., VLAN
            IDs or zero for untagged frames) to an ordered list of physical
            links if there are multiple physical links in the UNI and the link
            aggregation is ALL_ACTIVE. Note: In some cases the Port Conversation
            ID to Aggregation Link Map can be specified at the OVC End Point.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetLinkAggregation.yaml#/definitions/ConversationIdToAggregationLinkMap"
    meg:
        description:  >-
            MEF 26.2 §9.7 - Is a Down ENNI MEG MEP Enabled at the ENNI
            as described in MEF 30.1?
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    lagLinkMeg:
        description:  >-
            MEF 26.2 §9.8 - If Enabled the Service Provider MUST operate
            the LAG Link MEG on each link in the ENNI.
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    linkOAM:
        description:  >-
            MEF 26.2 §9.9 - Indicates whether Link OAM as described in
            Clause 57 of IEEE Std. 802.3 is supported on the ENNI.
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"

