---
"$schema": http://json-schema.org/draft-07/schema#
"$id": urn:mef:lso:spec:sonata:OperatorUNI:v1.0.0:inventory
title: 
    MEF LSO Sonata - Carrier Ethernet Operator UNI (Inventory) Product Specification
    # MEF Forum - Date: 20201220  Edit-level: 178
    # File: accessEline/inventory/carrierEthernetOperatorUni.yaml
description:  >-
    Operator UNI Service Attributes describe the agreement between
    the Service Provider and the Operator of the behavior observable
    at the UNI. These are distinct from the Subscriber UNI Service
    Attributes that describe the agreement between an Ethernet Service
    (EVC) Subscriber and the Ethernet Service Provider. All of these
    Service Attributes can be modified after initial provisioning of
    the UNI except the components of the List of Physical Links  and
    Link Aggregation-related attributes.
properties:
    listofPhysicalLinks:
        description:  >-
            MEF 26.2 §14.2, 14.3 - This Service Attribute combines several
            of the MEF 26.2 Objects into a single n-tuple that is consistent
            with the way this information is described in MEF 10.4. The value
            of the Operator UNI List of Physical Links Service Attribute is
            a list of 6-tuples of the form <id, physicalLink, synchronousEthernet,
            precisionTiming, uniConnectorType,uniConnectorGender>, with one
            list item for each physical link. The value of id is an identifier
            for the physical link. The value of physicalLink is the specific
            Ethernet physical layer type. synchronousEthernet indicates if
            synchronous Ethernet is used on the physical link and has the value
            Enabled or Disabled. The value of precisionTiming indicates if
            the Precision Time Protocol is used on the physical link and has
            the value Enabled or Disabled. The values of uniConnectorType and
            uniConnectorGender specify the type of connector used. Note that
            the id and the physicalLink come from the CarrierEthernetPhysicalLink
            class.
        # The cardinality of this list is important to several other Service Attributes
        type: array 
        minItems: 0
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetExternalInterfaces.yaml#/definitions/UniPhysicalLink"
    linkAggregation:
        description:  >-
            MEF 26.2 §14.5 - Service Attribute representing Link Aggregation
            types. NONE-No Link Aggregation is used. 2_LINK_ACTIVE_STANDBY-The
            SP network uses Link Aggregation as in either Clause 5.6.1 of IEEE
            Std 802.1AX-2008 [2] or Clause 6.7.1 of IEEE Std 802.1AX-2014 with
            one Link Aggregation Group(LAG) across the links supporting the
            UNI/ENNI such that all Service Frames are carried on only one of
            the two links when both links are operational. ALL_ACTIVE-The SP
            Network uses Link Aggregation as specified in Clause 5.3 of IEEE
            Std 802.1AX-2014, including the use of the version 2 LACPDUs as
            specified in Clause 5.3.1h of IEEE Std 802.1AZ-2014, with one Link
            Aggregation Group (LAG) across the links. OTHER-The Operator/Subscriber/Service
            Provider agree on another other resiliency mechanism.
        # See additional validation notes in the manual
        type: string
        enum:
            - "NONE"
            - "2_LINK_ACTIVE_STANDBY"
            - "ALL_ACTIVE"
            - "OTHER"
    aggregationLinkMap:
        description:  >-
            MEF 26.2 §14.6 and 802.1AX-2014 § 6.6.2.1 - A mapping of a
            list of Port Conversation IDs (i.e., VLAN IDs or zero for untagged
            frames) to an ordered list of physical links if there are multiple
            physical links in the UNI and the link aggregation is ALL_ACTIVE.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetLinkAggregation.yaml#/definitions/ConversationIdToAggregationLinkMap"
    maximumServiceFrameSize:
        description:  >-
            MEF 26.2 §14.8 - Specifies the maximum size of Service Frames
            that can be transmitted across the UNI.
        # See additional validation notes in the manual
        type: integer
        minimum: 1522
    defaultCeVlanId:
        description:  >-
            MEF 26.2 §14.9 - The value of the Operator UNI Default CE-VLAN
            ID is an integer that is the CE-VLAN ID value assigned to Untagged
            Service Frames and Priority Tagged Service Frames.
        type: integer
        minimum: 1
        maximum: 4094
    maximumNumberOfEndPoints:
        description:  >-
            MEF 26.2 §14.10 - The maximum number of OVC End Points that
            the Operator CEN can support at the UNI.
        type: integer
        minimum: 1
        maximum: 4094
    maximumNumberOfCeVlanIdsPerEndPoint:
        description:  >-
            MEF 26.2 §14.11 - An integer between 1 and 4094 inclusive that
            limits the number of C-Tag VLAN IDs that can map to each OVC End
            Point at the UNI.
        type: integer
        minimum: 1
        maximum: 4094
    ingressBandwidthProfile:
        description:  >-
            MEF 26.2 §14.12 - A single set Bandwidth Profile Flow parameters
            that covers all OVCs at the UNI. The value is either Disabled (empty
            array) or a BWP.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        maxItems: 1
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetBandwidthProfile.yaml#/definitions/BwpFlow"
    egressBandwidthProfile:
        description:  >-
            MEF 26.2 §14.13 - A single set of Bandwidth Profile Flow parameters
            that covers all OVCs at the UNI. The value is either Disabled (empty
            array) or a BWP.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        maxItems: 1
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetBandwidthProfile.yaml#/definitions/BwpFlow"
    linkOam:
        description:  >-
            MEF 26.2 §14.14 - Controls when and how Link OAM per IEEE Std
            802.3-2015 is run on the physical links in the UNI.
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    meg:
        description:  >-
            MEF 26.2 §14.15 - Indicates if the Service Provider has instantiated
            a MEG End Point (MEP) at the UNI Maintenance Entity Group (MEG)
            Level (ENABLED) or not (DISABLED).
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    lagLinkMeg:
        description:  >-
            MEF 26.2 §14.16 - Indicates if the Service Provider has instantiated
            a LAG Link MEG End Point (MEP) on each physical link in the UNI
            if the UNI has more than one physical link (ENABLED) or not (DISABLED).
        # See additional validation notes in the manual
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    tokenShare:
        description:  >-
            MEF 26.2 §14.18 - An attribute that indicates whether Bandwidth
            Profile Envelopes containing more than one Bandwidth Profile Flow
            are supported by the Service Provider at the Operator UNI.
        # See additional validation notes in the manual
        type: object
        $ref: "../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
    envelopes:
        description:  >-
            MEF 26.2 §14.19 - The Envelopes and Envelope Coupling Flag
            values to which Bandwidth Profile Flows can be mapped. Value is
            list of {envelopeID, couplingFlagForIndexZero}. Note: Envelopes
            for the UNI can also be specified at the OVC End Points associated
            with the UNI.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        uniqueItems: TRUE
        items:
            type: object
            $ref: "../common/carrierEthernetBandwidthProfile.yaml#/definitions/Envelope"
    l2cpAddressSet:
        description:  >-
            MEF 26.2 §14.20 and MEF 45.1 §8.1 - The subset of the Bridge
            Reserved Addresses that are Peered or Discarded (i.e. not Passed).
            The value CTB or CTB2 must be used for port-based (private) services
            and CTA for vlan-based (virtual private) services. Per MEF 45.1:
            If an OVC has an OVC End Point at a UNI, then the value of the
            Operator UNI L2CP Address Set Service Attribute MUST be the same
            as the OVC L2CP Address Set Service Attribute.
        # See additional validation notes in the manual
        type: string
        enum:
            - "CTA"
            - "CTB"
            - "CTB2"
    l2cpPeering:
        description:  >-
            MEF 26.2 §14.21 and  and MEF 45.1 §8.1 - L2CP Peering Service
            Attribute defined in MEF 45.1 specifies which protocols, if any,
            are peered at the UNI. The L2CP Peering service attribute value
            must be an empty list, or a list of entries identifying protocols
            to be Peered where each entry consists of {Destination Address,
            Protocol Identifier} or {Destination Address, Protocol Identifier,
            Link Identifier}.
        # See additional validation notes in the manual
        type: array 
        minItems: 0
        uniqueItems: FALSE
        items:
            type: object
            $ref: "../common/carrierEthernetL2cp.yaml#/definitions/L2cpPeering"
required:
    - listofPhysicalLinks
    - linkAggregation
    - maximumServiceFrameSize
    - maximumNumberOfEndPoints
    - maximumNumberOfCeVlanIdsPerEndPoint
    - ingressBandwidthProfile
    - egressBandwidthProfile
    - linkOam
    - meg
    - tokenShare
    - envelopes
    - l2cpAddressSet
    - l2cpPeering

